//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelefonRehberi_ok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE()
        {
            this.Emp_Man = new HashSet<Emp_Man>();
        }
    
        public int emp_id { get; set; }
        public string fname { get; set; }
        public string sname { get; set; }
        public Nullable<int> mng_id { get; set; }
        public Nullable<int> dep_id { get; set; }
        public string tel { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Man> Emp_Man { get; set; }
        public virtual Emp_Man Emp_Man1 { get; set; }
    }
}
